### PR TITLE
chore: Gitpodify ClassroomIO

### PR DESCRIPTION
**Pull request by obakeng-develops**
## What does this PR do?

This PR aims to create a Gitpod setup to simplify contributing to the repo via the browser.

Fixes # (issue)

N/A

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

To test this, you need to download the Gitpod Chrome Extension [here](https://chrome.google.com/webstore/detail/gitpod/dodmmooeoklaejobgleioelladacbeki) and then run the workspace in your account.

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

### CODE REVIEW

**Comment by obakeng-develops** [comment]
Hey @rotimi-best, on running the workspace, everything seems to be fine except when starting Supabase I get the following error - "ERROR: constraint "buckets_owner_fkey" of relation "buckets" does not exist (SQLSTATE 42704)".

I know what the error is saying but I can't seem to find a way to fix this. Would you know what I could do here?

**Comment by rotimi-best** [comment]
> Hey @rotimi-best, on running the workspace, everything seems to be fine except when starting Supabase I get the following error - "ERROR: constraint "buckets_owner_fkey" of relation "buckets" does not exist (SQLSTATE 42704)".
> 
> I know what the error is saying but I can't seem to find a way to fix this. Would you know what I could do here?


@obakeng-develops Bro you rock, thanks for working on this.

I think you need to just remove this line in the migration file

image

I can do that real quick and test it out

**Comment by rotimi-best** [comment]
@obakeng-develops I have gotten `supabase start` to run successfully.
image

However I think there are a couple of things left:

1. Setting ports and specifying the port that should open in the browser. This is an example from the gitpod setup of @formbricks
image

2. Copying the environment variables from `env.example` into `.env` for each project

3. One thing about environment variables here is getting the result of `supabase start` into `.env` of `apps/dashboard`. These are the variables specifically that we need:

```env
   PUBLIC_SUPABASE_URL=<API URL>
   PUBLIC_SUPABASE_ANON_KEY=<anon key>
   PUBLIC_SUPABASE_BUCKET_URL=<Inbucket URL>
 ```

**Comment by rotimi-best** [comment]
Closing this PR because it has been inactive by the original author for about 1 week.

I am taking over the PR in a different branch: https://github.com/rotimi-best/classroomio/pull/91

**Pull request closed without merging**
