### PR TITLE
docs: course landing page

### PR DESCRIPTION
**Pull request by hugolee003**
## What does this PR do?

Fixes # (Updated documentation for the course landing page)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [x] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the ClassroomIO Docs if changes were necessary

### CODE REVIEW

**Comment by hugolee003** [comment]
I just made a PR for the course landing page on the docs. You can check it out and let me know if you need corrections to be made.

**Comment by hugolee003** [comment]
I just made a PR for the course landing page on the docs. You can check it out and let me know if you need corrections to be made.

**Review by hugolee003 — COMMENTED** [review]
Has this been reviewed too?

**Review by rotimi-best — APPROVED** [review]
Thank you for the contribution 👍🏽🙏🏽

**Pull request merged**
