### PR TITLE
feat: classroomio blog v1

### LINKED ISSUE #139: Create classroomio blog
### Feature Description

The blog will be very simple. We don't have a design for this, instead we will be following a similar structure to documenso.

Visit documenso.com/blog, 

1. That is the first page that you need to implement
image

2. Click on any blog link and you will be redirected to a blog page. This is the second page you need to implement.
image

### Use Case

_No response_

### Proposed Solution

Follow this tutorial to implement blogs using markdown in svelte

https://joyofcode.xyz/sveltekit-markdown-blog

Ideally start from here
image

and end here
image

Please pay attention in this post that instead of `post` we should have `blog` and the routes you create should be in `apps/classroomio-com`

### Alternatives (optional)

_No response_

### Additional Context

_No response_

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

### PR DESCRIPTION
**Pull request by Chifez**
## What does this PR do?
This PR shows the implementation of the ClassroomIO blog

Fixes #139

https://github.com/rotimi-best/classroomio/assets/69228399/5f7847d1-81c9-4540-883c-5b0d32998836

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- run the dev server and go to classroomio landing page 
- click on blogs 

### Required

- [x] Filled out the "How to test" section in this PR
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

### CODE REVIEW

**Comment by rotimi-best** [comment]
@Chifez I noticed you didn't push any of the packages you installed?

**Comment by Chifez** [comment]
> @Chifez I noticed you didn't push any of the packages you installed?

yea,that was part of the issue i faced when i pushed initially,but that has been rectified

**Comment by Chifez** [comment]
this is the overrride behaviour i was taliking about,it is inheriting styles from somewhere that is affecting how the markedown is being redendered,this video just shows for headers but  it is also affecting the list item style too


https://github.com/rotimi-best/classroomio/assets/69228399/1697e0a2-54d1-443b-85d1-ce78d617468c

**Comment by rotimi-best** [comment]
@Chifez What does this code do?

image

**Review by rotimi-best — APPROVED** [review]
Great job following the tutorial @Chifez and getting everything to work.

Looks good to me

**Pull request merged**
