### PR TITLE
feat: dashboard billing

### PR DESCRIPTION
**Pull request by rotimi-best**
## What does this PR do?

To implement billing functionality into the dashboard. https://github.com/rotimi-best/classroomio/issues/9

### Requirements

- [ ] Show plan upgrade prompt on dashboard
- [ ] A modal showing all plans
- [ ] A user can pay for a plan
- [ ] Limit features within the application depending on plans.
  - [ ] Show in student dashboard, powered by ClassroomIO
- [ ] Show usage limits on students in Nav bar and Audience page.
- [ ] Add billing to settings. User can view current plan, downgrade or upgrade.

### Other Todos
- [ ] Create an automate email when a free user reaches their student limit
- [ ] Disable billing on selfhosted version of dashboard.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

### CODE REVIEW

**Comment by rotimi-best** [comment]
@Chifez Here is what I need your help with.

# Todo

- [ ] Implement this Call To Action (CTA) on the side bar of only the `dashboard` not the `lms`

image

- [ ] Upon clicking on the Upgrade Now button, show this kind of modal. Note, this screenshot of the modal is from ChatGPT upgrade popup. Just follow a similar pattern however use our data

image

## Note
For the content, please make sure to start `apps/classroomio-com` locally on the `billing` branch to see the lastest update to the pricing page.
image

The content of the pricing is coming from `packages/shared-constants/src/plans.json` and you can find how the content of the pricing page is displayed in this component

```
apps/classroomio-com/src/lib/Pricing/Pricing.svelte
```

**Comment by Chifez** [comment]
i just pushed my work here is a screenrecord of what it looks like

https://github.com/rotimi-best/classroomio/assets/69228399/bf924027-275b-4ee8-8ff1-45588155bcaa

**Comment by rotimi-best** [comment]
@Chifez Thanks, great job


A couple of feedbacks
1. Let there be spacing between the title of the plan and the pricing
2. Let the pricing cards have a border radius like on our site

**Comment by Chifez** [comment]
> @Chifez Thanks, great job
> 
> A couple of feedbacks
> 
> 1. Let there be spacing between the title of the plan and the pricing
> 2. Let the pricing cards have a border radius like on our site

alright

**Comment by Chifez** [comment]
updated
Screenshot (868)

**Comment by rotimi-best** [comment]
improve styling of upgrade modal for dark mode

https://github.com/rotimi-best/classroomio/assets/31730715/c9cfc0d6-cd09-428c-9b6f-fff718406664

**Comment by rotimi-best** [comment]
## Todo

- [x] Collect payment from users in dashboard
- [x] Show current plan in dashboard
- [ ] Limit features in app depending on plan
- [ ] Add classroomio branding to pages on free plan

**Pull request merged**
