### PR TITLE
ci: Documentation on Self hosted ClassroomIO with Docker

### LINKED ISSUE #44: Selfhost ClassroomIO
### Feature Description

A user should be able to run the whole classroomio stack via docker.

### Use Case

Anyone interested in selfhosting can do that in a few steps

### Proposed Solution

- Docker compose file to spin up the service
- Important to add how to selfhost supabase https://supabase.com/docs/guides/self-hosting/docker
- Some documentation on how to do it.

### Alternatives (optional)

_No response_

### Additional Context

_No response_

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

### PR DESCRIPTION
**Pull request by SabAlej**
## What does this PR do?

A user should be able to run the whole classroomio stack via docker. And change two links.

#Fixes #44 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [x] This change requires a documentation update

## How should this be tested?

Just follow the steps to setup the Docker in the Readme. Should work.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the ClassroomIO Docs if changes were necessary

### CODE REVIEW

**Comment by rotimi-best** [comment]
@SabAlej Great job on this.

I think I will need to update the issue cause your implementation is full setup of selhosting Supabase not using the cloud.

This is not a bad thing it just another functionality, but don't worry about it.

For now, once your PR is ready, can I ask you to add a video demo of how everything works?

**Comment by SabAlej** [comment]
Hello @rotimi-best I'm sorry, you're right about the issue. I can delete the docker config for supabase to leave it in the cloud. And yes, of course, I will make a video for the final PR. 
Let me know if there's another change to be made in order to walk the path for the growth of your project! 💪🏼😎🥳

**Comment by rotimi-best** [comment]
Hey @SabAlej, thank you so very much.

Please don't delete the docker configs, I can refine the issue title to match what you've implemented. It is actually needed right now in order for people to fully self host the whole stack.

Thanks.

**Comment by SabAlej** [comment]
Hi @rotimi-best I was getting errors with docker-compose, so I got back to try with a Dockerfile for dashboard only, but i ran into this:
dockerfile-dashboard

So, I think i'm going to need help and/or time to get to a successfull dockerization. Btw, I won't delete anything. 

If you have any suggestions to make this work faster, please let me know. Thank you!

**Comment by rotimi-best** [comment]
> Hi @rotimi-best I was getting errors with docker-compose, so I got back to try with a Dockerfile for dashboard only, but i ran into this: dockerfile-dashboard
> 
> So, I think i'm going to need help and/or time to get to a successfull dockerization. Btw, I won't delete anything.
> 
> If you have any suggestions to make this work faster, please let me know. Thank you!

This means basically that your computer ran out of memory.

Do you want to try any of the hosted services to test this out? maybe something like digital ocean or aws to test it all working.

**Comment by rotimi-best** [comment]
@SabAlej For now I will be closing this PR as it isn't actively worked on.

Whenever you are ready we can reopen it. Thanks

**Pull request closed without merging**
