### PR TITLE
fix: wrong background of short description field

### PR DESCRIPTION
**Pull request by Justinguu**
fixed the wrong background of short description field

Fixes: https://github.com/rotimi-best/classroomio/issues/34

### CODE REVIEW

**Comment by ib-best** [comment]
Thank you so much for this fix. Do you mind adding a screenshot or short demo in the description showing the issue was fixed 😀☺️

**Comment by rotimi-best** [comment]
Thank you so much for fixing this issue. Do you mind adding a screenshot or a video showing the issue is fixed? Thanks ☺️

**Comment by Justinguu** [comment]
Sure here you go.

**Comment by rotimi-best** [comment]
@Justinguu Not sure you added the image or demo. Can you add it to the PR description and attach the link of the issue in the PR description?

**Comment by Justinguu** [comment]
Screen Shot 2023-11-20 at 6 18 36 PM

**Review by rotimi-best — APPROVED** [review]
Thanks a lot for the PR  🎉 🎉 🎉 🎉 🎉 🎉  

Congrats on getting your first PR approved, merging now 😊 😊 😊

**Comment by rotimi-best** [comment]
@Justinguu have you joined our discord? If you have, can you shoot me a message, I would like to give you a shoutout.

Thanks a lot for the contribution

**Comment by Justinguu** [comment]
No, I haven't but I'd love to join the community!

**Comment by Justinguu** [comment]
May i have a link to the discord?

**Comment by rotimi-best** [comment]
Sure it is dub.sh/ciodiscord

**Comment by rotimi-best** [comment]
I see that link is expired, can you try this https://discord.gg/cmDRSS6Y

**Pull request merged**
